export const BASE_URL_BASE = 'https://cdn-api.co-vin.in/api';
export const BASE_URL = BASE_URL_BASE + '/v2';
export const GENERATE_OTP = '/auth/public/generateOTP';
export const CONFIRM_OTP = '/auth/public/confirmOTP';
export const GET_STATES = '/admin/location/states';
export const GET_DISTRICTS = '/admin/location/districts/';
export const GET_SESSIONS_CALENDAR = '/appointment/sessions/public/';
export const GET_SESSIONS_CALENDAR_BY_PIN =
  '/appointment/sessions/public/calendarByPin?pincode=';
export const GET_SESSIONS_FIND_BY_PIN =
  '/appointment/sessions/public/findByPin?pincode=';
